### ISSUE TITLE
Broken Oredict Registration [1.5.9]

### ISSUE THREAD

**Issue by npawk12** [draknyte1/GTplusplus#125]
[17:29:08] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name blockFluoriteOre has occurred. It adds an item (type: class gtPlusPlus.core.item.base.itemblock.ItemBlockGtBlock) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod GT++ report it to them!
[17:29:08] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[17:29:08] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[17:29:08] [Client thread/WARN] [FML]: *  at gregtech.api.util.GT_OreDictUnificator.registerOre(GT_OreDictUnificator.java:238)
[17:29:08] [Client thread/WARN] [FML]: *  at gtPlusPlus.core.item.base.itemblock.ItemBlockGtBlock.<init>(ItemBlockGtBlock.java:40)
[17:29:08] [Client thread/WARN] [FML]: *  at sun.reflect.GeneratedConstructorAccessor117.newInstance(Unknown Source)
[17:29:08] [Client thread/WARN] [FML]: *  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)...

Simillar errors occur with every alloy ingot block and frame. 
Using the latest GT from Github and IC2 2.2.827.

**Comment by draknyte1** [comment]
Refer to https://github.com/draknyte1/GTplusplus/issues/102.
