### ISSUE TITLE
Crash when breaking any block on existing world [1.6.05]

### ISSUE THREAD

**Issue by venturaguy101** [draknyte1/GTplusplus#139]
I am getting a crash when I break any block in my existing world.  I thought this was with the GT++ redstone cable but I noticed when I broke dirt and stone.  I appears to be in the harvestdrops function for GT++:

Note:  System information is psoted in the redstone cable issue #133
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 10/3/17 8:42 PM
Description: Ticking memory connection

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:630)
	at gtPlusPlus.core.handler.events.BlockEventHandler.harvestDrops(BlockEventHandler.java:123)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_598_BlockEventHandler_harvestDrops_HarvestDropsEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:162)
	at net.minecraft.block.Block.func_149690_a(Block.java:656)
	at net.minecraft.block.Block.func_149697_b(Block.java:648)
	at net.minecraft.block.Block.func_149636_a(Block.java:974)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:299)
	at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:217)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:498)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:630)
	at gtPlusPlus.core.handler.events.BlockEventHandler.harvestDrops(BlockEventHandler.java:123)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_598_BlockEventHandler_harvestDrops_HarvestDropsEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:162)
	at net.minecraft.block.Block.func_149690_a(Block.java:656)
	at net.minecraft.block.Block.func_149697_b(Block.java:648)
	at net.minecraft.block.Block.func_149636_a(Block.java:974)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:299)
	at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:217)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:498)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@5587135f
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Technus** [comment]
I informed alkalus bout this

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GTplusplus/commit/45cd37522fd80f935a34df0d3c34a2c2f1a73cd3

**Comment by Technus** [comment]
This comkit in our fork fixes it
