### ISSUE TITLE
Error after version 1.4.1.4

### ISSUE THREAD

**Issue by Amos1972** [draknyte1/GTplusplus#14]
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 9/22/16 7:58 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: gtPlusPlus/core/item/general/ItemCloakingDevice
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: gtPlusPlus/core/item/general/ItemCloakingDevice
	at gtPlusPlus.core.common.CommonProxy.init(CommonProxy.java:87)
	at gtPlusPlus.core.proxy.ClientProxy.init(ClientProxy.java:25)
	at gtPlusPlus.GTplusplus.init(GTplusplus.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 18 more
Caused by: java.lang.ClassNotFoundException: gtPlusPlus.core.item.general.ItemCloakingDevice
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 47 more
Caused by: java.lang.NoClassDefFoundError: baubles/api/IBauble
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 49 more
Caused by: java.lang.ClassNotFoundException: baubles.api.IBauble
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 53 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows XP (x86) version 5.1
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 382394232 bytes (364 MB) / 823562240 bytes (785 MB) up to 912719872 bytes (870 MB)
	JVM Flags: 7 total; -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx896m -XX:PermSize=128m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHI	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHI	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHI	Aroma1997Core{1.0.2.15} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.15.jar) 
	UCHI	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHI	OpenComputers|Core{1.6.0.965-dev} [OpenComputers (Core)] (minecraft.jar) 
	UCHI	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHI	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHI	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHI	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHI	Aroma1997CoreHelper{1.0.2.15} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.15.jar) 
	UCHI	AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar) 
	UCHI	asielib{0.4.6} [asielib] (AsieLib-1.7.10-0.4.6.100-dev.jar) 
	UCHI	bdlib{1.9.2.104} [BD Lib] (bdlib-1.9.2.104-mc1.7.10.jar) 
	UCHI	betterbuilderswands{0.5.3} [Better Builder's Wands] (BetterBuildersWands-0.5.3-1.7.10r73+0938a64.jar) 
	UCHI	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHI	catwalks{2.0.4} [Catwalks Mod] (catwalks-2.0.4.jar) 
	UCHI	catwalkmod{x.x.x} [Legacy Catwalk Compat] (catwalks-2.0.4.jar) 
	UCHI	ChestTransporter{2.0.3} [Chest Transporter] (ChestTransporter-2.0.3-MC1.7.10.jar) 
	UCHI	endercore{1.7.10-0.2.0.36_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.36_beta.jar) 
	UCHI	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCHI	IC2{2.2.825-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.825-experimental.jar) 
	UCHI	magicalcrops{4.0.0_PUBLIC_BETA_3} [Magical Crops] (magicalcrops-4.0.0_PUBLIC_BETA_3.jar) 
	UCHI	gregtech{MC1710} [GregTech] (gregtech-5.09.23pre6.jar) 
	UCHI	ImmibisCore{59.0.8} [Immibis Core] (immibis-core-59.0.8.jar) 
	UCHI	RedLogic{59.1.9} [RedLogic] (redlogic-59.1.9.jar) 
	UCHI	OpenComputers{1.6.0.965-dev} [OpenComputers] (OpenComputers-MC1.7.10-1.6.0.965-dev-universal.jar) 
	UCHI	computronics{1.6.1} [Computronics] (Computronics-1.7.10-1.6.1.100-dev-OC1.6.jar) 
	UCHI	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b197.jar) 
	UCHI	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCHI	GraviSuiteReloaded{1.7.10-0.9.1} [GraviSuiteReloaded] (GraviSuite_Reloaded-1.7.10-0.9.1.jar) 
	UCHE	miscutils{1.4.8-prerelease} [GT++] (GT-PlusPlus-1.4.8-prerelease.jar) 
	UCHI	GTTweaker{1.1.0} [GTTweaker] (GTTweaker-1.7.10-1.1.0.jar) 
	UCHI	IC2NuclearControl{2.4.1a} [Nuclear Control 2] (IC2NuclearControl-2.4.1a.jar) 
	UCHI	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHI	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHI	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHI	warpbook{2.0.null} [Warp Book] (warpbook-1.7.10_2.0.36.jar) 
	UCHI	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 355.98' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	List of loaded APIs: 
		* appliedenergistics2|API (rv3) from appliedenergistics2-rv3-beta-6.jar
		* asielibAPI (1.1) from AsieLib-1.7.10-0.4.6.100-dev.jar
		* asielibAPI|chat (1.0) from AsieLib-1.7.10-0.4.6.100-dev.jar
		* asielibAPI|tile (1.0) from AsieLib-1.7.10-0.4.6.100-dev.jar
		* asielibAPI|tool (1.1) from AsieLib-1.7.10-0.4.6.100-dev.jar
		* CoFHAPI (1.7.10R1.0.13) from EnderCore-1.7.10-0.2.0.36_beta.jar
		* CoFHAPI|block (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* CoFHAPI|energy (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* CoFHAPI|inventory (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* CoFHAPI|item (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* CoFHAPI|tileentity (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* CoFHAPI|transport (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* computronicsAPI (1.3) from Computronics-1.7.10-1.6.1.100-dev-OC1.6.jar
		* computronicsAPI|audio (1.0) from Computronics-1.7.10-1.6.1.100-dev-OC1.6.jar
		* computronicsAPI|chat (1.3) from Computronics-1.7.10-1.6.1.100-dev-OC1.6.jar
		* computronicsAPI|multiperipheral (1.1) from Computronics-1.7.10-1.6.1.100-dev-OC1.6.jar
		* computronicsAPI|tape (1.0) from Computronics-1.7.10-1.6.1.100-dev-OC1.6.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.3.0.429_beta.jar
		* IC2API (1.0) from industrialcraft-2-2.2.825-experimental.jar
		* NuclearControlAPI (v1.0.5) from IC2NuclearControl-2.4.1a.jar
		* OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.965-dev-universal.jar
		* OpenComputersAPI|Core (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.965-dev-universal.jar
		* OpenComputersAPI|Driver (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.965-dev-universal.jar
		* OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.965-dev-universal.jar
		* OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.965-dev-universal.jar
		* OpenComputersAPI|FileSystem (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.965-dev-universal.jar
		* OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.965-dev-universal.jar
		* OpenComputersAPI|Machine (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.965-dev-universal.jar
		* OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.965-dev-universal.jar
		* OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.965-dev-universal.jar
		* OpenComputersAPI|Prefab (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.965-dev-universal.jar
	EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

**Comment by draknyte1** [comment]
I forgot to check if Baubles is installed, as these items require it.
>  java.lang.NoClassDefFoundError: baubles/api/IBauble

Lemme push a hotfix within the next day. Otherwise (There's a lack of downsides) just install Baubles for the time being, it's a small mod and allows extra gear slots. (Belts, Rings and Amulets)

https://mods.curse.com/mc-mods/minecraft/227083-baubles/2224857

**Comment by Amos1972** [comment]
yeah that was the problem

**Comment by draknyte1** [comment]
Thanks for the confirmation. 
I'll mark this as fixed and it'll roll out in the next release. Be it another pre-release or not.

**Comment by draknyte1** [comment]
https://github.com/draknyte1/GTplusplus/releases/tag/1.4.8.2-Pre

Baubles and Server-Side classes both fixes in this release.
