### ISSUE TITLE
Crash the server due to client-side methods [1.6.103-prerelease][GTNH modpack]

### ISSUE THREAD

**Issue by Remint32** [draknyte1/GTplusplus#169]
**GT New Horizons modpack 2.0.2.3** (latest, **after** previous "fix" client-side methods)
1. **gregtech-5.09.32.13** and **industrialcraft-2-2.2.828a-experimental**.
2. Just start server and wait loading.
3. Yes. On **forge-1.7.10-10.13.4.1614-1.7.10** or/and **Thermos 1.7.10**.
4. It was the server.
5. It is a serious problem.

_Logs attached as file_
[**Thermos** crash-2017-12-16_19.09.56-server.txt](https://github.com/draknyte1/GTplusplus/files/1565057/crash-2017-12-16_19.09.56-server.txt)
[**Clean Forge** crash-2017-12-16_19.58.29-server.txt](https://github.com/draknyte1/GTplusplus/files/1565054/crash-2017-12-16_19.58.29-server.txt)

```
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
    at gtPlusPlus.GTplusplus.initAnalytics(GTplusplus.java:187)
    at gtPlusPlus.GTplusplus.preInit(GTplusplus.java:82)

.  .  .

    UCE    miscutils{1.6.102-prerelease} [GT++] (GT-PlusPlus-1.6.103-prerelease.jar)
```

**Comment by Dream-Master** [comment]
Gregtech New Horizons Version 2.0.2.3 newest update.
