### ISSUE TITLE
crash with thaumcraft

### ISSUE THREAD

**Issue by mightydanp** [draknyte1/GTplusplus#22]
java.lang.IllegalArgumentException: No enum constant gtPlusPlus.xmod.gregtech.api.enums.GregtechOrePrefixes.GT_Materials.VoidMetal
	at java.lang.Enum.valueOf(Unknown Source)
	at gtPlusPlus.xmod.gregtech.api.enums.GregtechOrePrefixes$GT_Materials.valueOf(GregtechOrePrefixes.java:295)
	at gtPlusPlus.xmod.gregtech.registration.gregtech.GregtechConduits.superConductorFactory(GregtechConduits.java:138)
	at gtPlusPlus.xmod.gregtech.registration.gregtech.GregtechConduits.run1(GregtechConduits.java:58)
	at gtPlusPlus.xmod.gregtech.registration.gregtech.GregtechConduits.run(GregtechConduits.java:42)
	at gtPlusPlus.xmod.gregtech.HANDLER_GT.init(HANDLER_GT.java:36)
	at gtPlusPlus.core.handler.COMPAT_IntermodStaging.init(COMPAT_IntermodStaging.java:23)
	at gtPlusPlus.core.common.CommonProxy.init(CommonProxy.java:95)
	at gtPlusPlus.core.proxy.ClientProxy.init(ClientProxy.java:28)
	at gtPlusPlus.GTplusplus.init(GTplusplus.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by draknyte1** [comment]
Fixed from this release.
https://github.com/draknyte1/GTplusplus/releases/tag/v1.4.8.6

Fixed here - https://github.com/draknyte1/GTplusplus/commit/9592da6b803f19174f44ec6d551601aae4aa87ce
