### ISSUE TITLE
GTNH - Delta Crash - XP Converter

### ISSUE THREAD

**Issue by mitchej123** [draknyte1/GTplusplus#370]
# Issue Title  
GTNH Crash on Delta server - XP Converter

```
---- Minecraft Crash Report ----
// My bad.

Time: 9/3/18 1:35 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at gtPlusPlus.core.tileentities.general.TileEntityXpConverter.drain(TileEntityXpConverter.java:118)
    at crazypants.enderio.conduit.liquid.EnderLiquidConduitNetwork.extractFrom(EnderLiquidConduitNetwork.java:50)
    at crazypants.enderio.conduit.liquid.EnderLiquidConduit.doExtract(EnderLiquidConduit.java:253)
    at crazypants.enderio.conduit.liquid.EnderLiquidConduit.updateEntity(EnderLiquidConduit.java:232)
    at crazypants.enderio.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:254)
    at com.enderio.core.common.TileEntityEnder.func_145845_h(TileEntityEnder.java:45)
    at net.minecraft.world.World.func_72939_s(World.java:2583)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
    at java.lang.Thread.run(Thread.java:748)
```

Line 118:
```
line 118: if (fluid.amount < drained)
```

Earlier on:
```
        final FluidStack fluid_Essence = this.tankEssence.getFluid();
        final FluidStack fluid_Xp = this.tankLiquidXp.getFluid();
        if ((fluid_Essence == null) && (fluid_Xp == null)) {  // <-- Possible only one is null
            return null;
        }
```

My guess is one of fluid_Essence or fluid_Xp is null, but not both, and thus the null pointer exception when it tries fluid.amount.

## Current Behavior
Crash

## Possible Solution
Return if either are null, or handle null fluids.

## Context
Passing a long a crash from the Delta server.

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  GTNH
 * Version used: Not sure - 2.0.4.6 probably

Also include:
 * Gregtech version:
 * IC2 version:
 * Java version:
 * Operating System:

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [X]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [X]    Multi Player?

**Comment by mitchej123** [comment]
@Dream-Master perhaps you can add a bit more context for the Delta crash.

**Comment by Wolozo7** [comment]
Experience Converter was put down next to an Experience Obelisk with an Ender Fluid Conduit between them. 

![image](https://user-images.githubusercontent.com/34921674/45002297-6d36c180-afd5-11e8-832e-a57548f419d3.png)

**Comment by Dream-Master** [comment]
I can add only the full log if needed.

**Comment by draknyte1** [comment]
Fixed this before lunch time when I ducked home between interviews.
Just haven't committed it yet.
