### ISSUE TITLE
Matter Fabrication CPU with strange work.

### ISSUE THREAD

**Issue by yukieiji** [draknyte1/GTplusplus#405]
# Issue Title  
Matter Fabrication CPU with strange work[GT-PlusPlus-1.7.02.09]

## Expected Behavior
Matter Fabrication CPU work well.

## Current Behavior
Opening GUI is strange... Server kick on multiplay and crash on single.
And only Recycling works until restart(World or Server).
After restart only UUM producing work with no programming circuit.
That working always spam log.

- Multiplay ErrorLog
[22:00:18 WARN]: Failed to handle packet for /( My IP Address xD )
java.lang.IndexOutOfBoundsException: Index: 36, Size: 36
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_191]
	at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_191]
	at gregtech.api.gui.GT_Container.func_75144_a(GT_Container.java:106) ~[GT_Container.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2075) ~[nh.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
- SinglePlay CrashReport 
[crash-2019-01-05_22.10.22-server.txt](https://github.com/draknyte1/GTplusplus/files/2729522/crash-2019-01-05_22.10.22-server.txt)

- Log spam
[22:04:47 INFO]: Doing Recipe.
[22:04:47 INFO]: 1.
[22:04:47 INFO]: 2.
[22:04:47 INFO]: 2.x. Returning Cached Result.
[22:04:47 INFO]: 3.
[22:04:47 INFO]: 4.
[22:04:47 INFO]: Doing Recipe.
[22:04:47 INFO]: 1.
[22:04:47 INFO]: 2.
[22:04:47 INFO]: 2.x. Returning Cached Result.
[22:04:47 INFO]: 3.
[22:04:47 INFO]: 4.
[22:04:52 INFO]: Doing Recipe.
[22:04:52 INFO]: 1.
[22:04:52 INFO]: 2.
[22:04:52 INFO]: 2.x. Returning Cached Result.
[22:04:52 INFO]: 3.
[22:04:52 INFO]: 4.
[22:04:52 INFO]: Doing Recipe.
[22:04:52 INFO]: 1.
[22:04:52 INFO]: 2.
[22:04:52 INFO]: 2.x. Returning Cached Result.
[22:04:52 INFO]: 3.
[22:04:52 INFO]: 4.

## Steps to Reproduce (for bugs)
Server kick and Clash.
 1.Opning Matter Fabrication CPU GUI
 2.Left click on Inventory slot 9 in the opened state.

## Game Environment
 * Modpack Name: GTNH
 * Version used:ver2.0.6.2

Also include:
 * Gregtech version:gregtech-5.09.33.04
 * IC2 version:industrialcraft-2-2.2.828a-experimental
 * Java version:1.8.0_191
 * Operating System:Windows 10 Pro and Cent OS7

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
Fixed both issues here - https://github.com/draknyte1/GTplusplus/commit/cd946fdf9637eff1879726dc514a29c58377cdd9.
